#!/usr/bin/env python3
# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.

"""Create, inspect, and safely retire isolated PTOAS workspaces."""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

METADATA = ".ptoas-workspace.json"


class ManagerError(RuntimeError):
    """A safe, user-actionable manager failure."""


def run(command: list[str], *, cwd: Path | None = None, env: dict[str, str] | None = None) -> subprocess.CompletedProcess[str]:
    return subprocess.run(command, cwd=cwd, env=env, text=True, capture_output=True, check=False)


def git(repo: Path, *args: str) -> subprocess.CompletedProcess[str]:
    return run(["git", "-C", str(repo), *args])


def existing_dir(value: str, label: str) -> Path:
    path = Path(value).expanduser().resolve()
    if not path.is_dir():
        raise ManagerError(f"{label} does not exist or is not a directory: {path}")
    return path


def ensure_repo(repo: Path) -> None:
    if git(repo, "rev-parse", "--show-toplevel").returncode != 0:
        raise ManagerError(f"not a Git repository: {repo}")


def is_registered_worktree(repo: Path, workspace: Path) -> bool:
    result = git(repo, "worktree", "list", "--porcelain")
    roots = {
        Path(line.removeprefix("worktree ")).resolve()
        for line in result.stdout.splitlines()
        if line.startswith("worktree ")
    }
    return workspace.resolve() in roots


def load_metadata(workspace: Path) -> dict[str, Any]:
    path = workspace / METADATA
    if not path.is_file():
        raise ManagerError(f"missing {METADATA}: {workspace}")
    try:
        metadata = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ManagerError(f"cannot read {path}: {exc}") from exc
    if not isinstance(metadata, dict) or not metadata.get("repo") or not metadata.get("branch"):
        raise ManagerError(f"invalid workspace metadata: {path}")
    return metadata


def write_metadata(workspace: Path, metadata: dict[str, Any]) -> None:
    (workspace / METADATA).write_text(
        json.dumps(metadata, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )


def write_env(workspace: Path, metadata: dict[str, Any]) -> None:
    import shlex

    quote = shlex.quote
    lines = [
        "#!/usr/bin/env bash",
        "# Generated by ptoas-workspace-manager; source this file.",
        f"export PTO_SOURCE_DIR={quote(metadata['workspace'])}",
        f"export PTO_BUILD_DIR={quote(metadata['build_dir'])}",
        f"export LLVM_BUILD_DIR={quote(metadata['llvm_build_dir'])}",
        f"export PYTHON_BIN={quote(metadata['python_bin'])}",
        'source "$PTO_SOURCE_DIR/.venv/bin/activate"',
    ]
    if metadata.get("ccache_dir"):
        lines.append(f"export CCACHE_DIR={quote(metadata['ccache_dir'])}")
    if metadata.get("cann_env"):
        lines.append(f"source {quote(metadata['cann_env'])}")
    lines.append('export PTOAS_WORKSPACE_METADATA="$PTO_SOURCE_DIR/.ptoas-workspace.json"')
    path = workspace / "env.sh"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    path.chmod(0o755)


def create(args: argparse.Namespace) -> int:
    for value, label in (
        (args.repo, "--repo or PTOAS_REPO"),
        (args.workspace_root, "--workspace-root or PTOAS_WORKSPACE_ROOT"),
        (args.build_root, "--build-root or PTOAS_BUILD_ROOT"),
        (args.llvm_build_dir, "--llvm-build-dir or LLVM_BUILD_DIR"),
    ):
        if not value:
            raise ManagerError(f"{label} is required")
    repo = existing_dir(args.repo, "repository")
    ensure_repo(repo)
    if not args.name or Path(args.name).name != args.name or args.name in {".", ".."}:
        raise ManagerError("--name must be a single non-empty directory name")
    workspace_root = Path(args.workspace_root).expanduser().resolve()
    build_root = Path(args.build_root).expanduser().resolve()
    workspace = workspace_root / args.name
    build_dir = build_root / args.name
    if workspace.exists():
        raise ManagerError(f"workspace path already exists: {workspace}")
    if build_dir.exists():
        raise ManagerError(f"build path already exists: {build_dir}")
    llvm = existing_dir(args.llvm_build_dir, "LLVM_BUILD_DIR")
    for forbidden, label in ((repo, "repository"), (workspace, "workspace"), (llvm, "LLVM_BUILD_DIR")):
        if build_dir == forbidden:
            raise ManagerError(f"build directory must not equal the {label}: {build_dir}")
    base_python = Path(args.base_python or sys.executable).expanduser().resolve()
    if not base_python.is_file() or not os.access(base_python, os.X_OK):
        raise ManagerError(f"base Python is not executable: {base_python}")
    cann_env = Path(args.cann_env).expanduser().resolve() if args.cann_env else None
    if cann_env and not cann_env.is_file():
        raise ManagerError(f"CANN environment script does not exist: {cann_env}")
    ccache_dir = Path(args.ccache_dir).expanduser().resolve() if args.ccache_dir else None
    if ccache_dir:
        ccache_dir.mkdir(parents=True, exist_ok=True)
    branch = args.branch or f"feature/{args.name}"
    workspace_root.mkdir(parents=True, exist_ok=True)
    build_root.mkdir(parents=True, exist_ok=True)

    try:
        added = git(repo, "worktree", "add", "-b", branch, str(workspace), args.base_ref)
        if added.returncode != 0:
            raise ManagerError(added.stderr.strip() or "git worktree add failed")
        for generated in (workspace / ".venv", workspace / METADATA, workspace / "env.sh"):
            if generated.exists():
                raise ManagerError(f"managed path already exists in the source tree: {generated}")
        venv_command = [str(base_python), "-m", "venv"]
        if args.system_site_packages:
            venv_command.append("--system-site-packages")
        venv_command.append(str(workspace / ".venv"))
        venv = run(venv_command)
        if venv.returncode != 0:
            raise ManagerError(venv.stderr.strip() or "python -m venv failed")
        metadata = {
            "version": 1,
            "repo": str(repo),
            "workspace": str(workspace),
            "branch": branch,
            "base_ref": args.base_ref,
            "build_dir": str(build_dir),
            "llvm_build_dir": str(llvm),
            "base_python": str(base_python),
            "python_bin": str(workspace / ".venv/bin/python"),
            "cann_env": str(cann_env) if cann_env else None,
            "ccache_dir": str(ccache_dir) if ccache_dir else None,
            "system_site_packages": args.system_site_packages,
        }
        write_metadata(workspace, metadata)
        write_env(workspace, metadata)
        if not args.skip_install:
            quick_install = workspace / "quick_install.sh"
            if not quick_install.is_file():
                raise ManagerError("quick_install.sh is missing from the worktree")
            install_env = os.environ.copy()
            install_env.update({
                "LLVM_BUILD_DIR": str(llvm),
                "PTO_BUILD_DIR": str(build_dir),
                "PYTHON_BIN": str(workspace / ".venv/bin/python"),
            })
            if ccache_dir:
                install_env["CCACHE_DIR"] = str(ccache_dir)
            installed = subprocess.run([str(quick_install), "-v"], cwd=workspace, env=install_env, check=False)
            if installed.returncode != 0:
                raise ManagerError("quick_install.sh failed (see output above)")
        print(json.dumps(metadata, indent=2, sort_keys=True))
        print(f"Created workspace: {workspace}")
        print(f"Activate with: source {workspace}/env.sh")
        return 0
    except Exception:
        if workspace.exists() and is_registered_worktree(repo, workspace):
            git(repo, "worktree", "remove", "--force", str(workspace))
        if build_dir.exists():
            shutil.rmtree(build_dir)
        raise


def merged_pr(repo: Path, branch: str) -> dict[str, Any]:
    if shutil.which("gh") is None:
        raise ManagerError("gh is required to verify that the pull request is merged")
    result = run(
        ["gh", "pr", "list", "--head", branch, "--state", "merged", "--limit", "100",
         "--json", "number,url,mergedAt,headRefOid"],
        cwd=repo,
    )
    if result.returncode != 0:
        raise ManagerError(result.stderr.strip() or "gh could not query pull requests")
    try:
        prs = json.loads(result.stdout)
    except json.JSONDecodeError as exc:
        raise ManagerError(f"gh returned invalid pull request data: {exc}") from exc
    if not prs:
        raise ManagerError(f"no merged pull request found for branch {branch}")
    return max(prs, key=lambda item: item.get("mergedAt") or "")


def head_contained_in_pr(repo: Path, workspace: Path, pr: dict[str, Any]) -> str | None:
    """Return None when the worktree HEAD is contained in the merged PR head,
    otherwise a human-readable reason why the workspace is not safe to destroy.

    A clean worktree is not enough: local commits that were never pushed (or
    were pushed after the PR merged) would be silently deleted. Requiring HEAD
    to be an ancestor of the PR's head commit proves every local commit was
    part of the merged pull request. It also rejects --head matches from an
    unrelated fork branch that happens to share the name.
    """
    head_oid = pr.get("headRefOid")
    if not head_oid:
        return "merged pull request has no head commit information"
    if git(repo, "cat-file", "-e", f"{head_oid}^{{commit}}").returncode != 0:
        fetched = git(repo, "fetch", "origin", head_oid)
        if fetched.returncode != 0 or git(repo, "cat-file", "-e", f"{head_oid}^{{commit}}").returncode != 0:
            return f"cannot fetch merged pull request head commit {head_oid}"
    if git(workspace, "merge-base", "--is-ancestor", "HEAD", head_oid).returncode != 0:
        return f"local commits on {workspace} are not contained in merged PR head {head_oid}"
    return None


def inspect_workspace(workspace: Path) -> tuple[dict[str, Any], dict[str, Any]]:
    metadata = load_metadata(workspace)
    repo = existing_dir(str(metadata["repo"]), "repository")
    ensure_repo(repo)
    if not is_registered_worktree(repo, workspace):
        raise ManagerError(f"path is not a registered Git worktree: {workspace}")
    branch_result = git(workspace, "symbolic-ref", "--short", "HEAD")
    branch = branch_result.stdout.strip()
    if branch != metadata["branch"]:
        raise ManagerError(f"metadata branch {metadata['branch']} does not match worktree branch {branch or 'detached'}")
    changes = git(workspace, "status", "--porcelain=v1", "--untracked-files=all")
    manager_files = {METADATA, "env.sh"}
    unexpected_changes = []
    for line in changes.stdout.splitlines():
        path = line[3:]
        if " -> " in path:
            path = path.split(" -> ", 1)[1]
        if line.startswith("?? ") and (path in manager_files or path.startswith(".venv/")):
            continue
        unexpected_changes.append(line)
    clean = changes.returncode == 0 and not unexpected_changes
    clean_reason = "worktree is clean" if clean else "worktree has staged, unstaged, or untracked changes"
    pr = None
    pr_error = None
    containment_error = None
    try:
        pr = merged_pr(repo, branch)
        containment_error = head_contained_in_pr(repo, workspace, pr)
    except ManagerError as exc:
        pr_error = str(exc)
    report = {
        "workspace": str(workspace),
        "branch": branch,
        "clean": clean,
        "clean_reason": clean_reason,
        "merged_pr": pr,
        "pr_error": pr_error,
        "containment_error": containment_error,
        "eligible": clean and pr is not None and containment_error is None,
    }
    return metadata, report


def status(args: argparse.Namespace) -> int:
    _, report = inspect_workspace(existing_dir(args.workspace, "workspace"))
    print(json.dumps(report, indent=2, sort_keys=True))
    return 0 if report["eligible"] else 1


def validated_build_dir(metadata: dict[str, Any], repo: Path, workspace: Path) -> Path:
    """Resolve the recorded build directory, refusing anything dangerous.

    The metadata file is just a JSON document; never feed an unchecked path
    from it into rmtree.
    """
    raw = metadata.get("build_dir")
    if not raw:
        raise ManagerError("workspace metadata has no build_dir")
    build_dir = Path(str(raw)).expanduser().resolve()
    protected = [repo, workspace, Path.home(), Path(build_dir.anchor)]
    llvm = metadata.get("llvm_build_dir")
    if llvm:
        protected.append(Path(str(llvm)).expanduser().resolve())
    for path in protected:
        root = path.resolve()
        if build_dir == root:
            raise ManagerError(f"refusing to remove unsafe build directory: {build_dir}")
    for path in (repo, workspace):
        if build_dir in path.resolve().parents:
            raise ManagerError(f"build directory is an ancestor of a protected path: {build_dir}")
    return build_dir


def destroy(args: argparse.Namespace) -> int:
    workspace = existing_dir(args.workspace, "workspace")
    metadata, report = inspect_workspace(workspace)
    print(json.dumps(report, indent=2, sort_keys=True))
    if not report["eligible"]:
        print("Not safe to destroy; no files were changed.", file=sys.stderr)
        return 1
    if not args.yes:
        print("Eligible for destruction. Re-run with --yes to remove the worktree and build directory.")
        return 0
    if Path.cwd().resolve() == workspace or str(Path.cwd().resolve()).startswith(str(workspace) + os.sep):
        raise ManagerError("refusing to remove the current working directory or one of its children")
    repo = existing_dir(str(metadata["repo"]), "repository")
    # These are manager-owned files. Remove only these known paths so Git can
    # unregister the worktree; all other untracked paths were already a gate.
    venv = workspace / ".venv"
    if venv.exists():
        shutil.rmtree(venv)
    for generated in (workspace / METADATA, workspace / "env.sh"):
        if generated.exists():
            generated.unlink()
    removed = git(repo, "worktree", "remove", str(workspace))
    if removed.returncode != 0:
        raise ManagerError(removed.stderr.strip() or "git worktree remove failed")
    build_dir = validated_build_dir(metadata, repo, workspace)
    if build_dir.exists():
        shutil.rmtree(build_dir)
    if args.delete_branch:
        deleted = git(repo, "branch", "-D", str(metadata["branch"]))
        if deleted.returncode != 0:
            raise ManagerError(deleted.stderr.strip() or "local branch deletion failed after workspace removal")
    print(f"Destroyed workspace: {workspace}")
    print(f"Shared LLVM/CANN resources were preserved: {metadata['llvm_build_dir']}")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    commands = parser.add_subparsers(dest="command", required=True)
    create_parser = commands.add_parser("create")
    create_parser.add_argument("--repo", default=os.environ.get("PTOAS_REPO"))
    create_parser.add_argument("--name", required=True)
    create_parser.add_argument("--workspace-root", default=os.environ.get("PTOAS_WORKSPACE_ROOT"))
    create_parser.add_argument("--build-root", default=os.environ.get("PTOAS_BUILD_ROOT"))
    create_parser.add_argument("--llvm-build-dir", default=os.environ.get("LLVM_BUILD_DIR"))
    create_parser.add_argument("--base-python", default=os.environ.get("PTOAS_BASE_PYTHON"))
    create_parser.add_argument("--base-ref", default=os.environ.get("PTOAS_BASE_REF", "HEAD"))
    create_parser.add_argument("--branch", default=os.environ.get("PTOAS_BRANCH"))
    create_parser.add_argument("--cann-env", default=os.environ.get("CANN_ENV_SCRIPT"))
    create_parser.add_argument("--ccache-dir", default=os.environ.get("CCACHE_DIR"))
    create_parser.add_argument("--no-system-site-packages", dest="system_site_packages", action="store_false")
    create_parser.add_argument("--skip-install", action="store_true")
    create_parser.set_defaults(system_site_packages=True, func=create)
    for name, function in (("status", status), ("destroy", destroy)):
        command = commands.add_parser(name)
        command.add_argument("--workspace", required=True)
        command.set_defaults(func=function)
    commands.choices["destroy"].add_argument("--yes", action="store_true")
    commands.choices["destroy"].add_argument("--delete-branch", action="store_true")
    return parser


def main() -> int:
    try:
        args = build_parser().parse_args()
        return args.func(args)
    except ManagerError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
