#!/usr/bin/env bash
set -euo pipefail

# PTOAS bootstrap script
# This script follows README.md and sets up:
# 1) Python/build dependencies
# 2) LLVM/MLIR (release/19.x) build tree
# 3) PTOAS build + install
# 4) Runtime environment script and optional ~/.bashrc wiring

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PTO_SOURCE_DIR="${PTO_SOURCE_DIR:-$SCRIPT_DIR}"
WORKSPACE_DIR="${WORKSPACE_DIR:-$(cd "$PTO_SOURCE_DIR/.." && pwd)}"
LLVM_SOURCE_DIR="${LLVM_SOURCE_DIR:-$WORKSPACE_DIR/llvm-project}"
LLVM_BUILD_DIR="${LLVM_BUILD_DIR:-$LLVM_SOURCE_DIR/build-shared}"
PTO_INSTALL_DIR="${PTO_INSTALL_DIR:-$PTO_SOURCE_DIR/install}"
LLVM_BRANCH="${LLVM_BRANCH:-release/19.x}"

UPDATE_BASHRC=1
if [[ "${1:-}" == "--no-bashrc" ]]; then
  UPDATE_BASHRC=0
fi

log() {
  printf '[bootstrap] %s\n' "$*"
}

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    printf '[bootstrap][error] Missing required command: %s\n' "$1" >&2
    exit 1
  fi
}

install_python_deps() {
  log "Installing Python dependencies (cmake, ninja, numpy, pybind11<3)..."
  python3 -m pip install --user --break-system-packages \
    "cmake" "ninja" "numpy" "pybind11<3"
}

clone_or_update_llvm() {
  mkdir -p "$WORKSPACE_DIR"
  if [[ ! -d "$LLVM_SOURCE_DIR/.git" ]]; then
    log "Cloning llvm-project ($LLVM_BRANCH) into $LLVM_SOURCE_DIR ..."
    git clone --depth 1 --branch "$LLVM_BRANCH" \
      https://github.com/llvm/llvm-project.git "$LLVM_SOURCE_DIR"
  else
    log "llvm-project already exists at $LLVM_SOURCE_DIR; ensuring branch $LLVM_BRANCH ..."
    git -C "$LLVM_SOURCE_DIR" fetch --depth 1 origin "$LLVM_BRANCH"
    git -C "$LLVM_SOURCE_DIR" checkout "$LLVM_BRANCH"
  fi
}

configure_llvm() {
  log "Configuring LLVM/MLIR at $LLVM_BUILD_DIR ..."
  cmake -G Ninja \
    -S "$LLVM_SOURCE_DIR/llvm" \
    -B "$LLVM_BUILD_DIR" \
    -DLLVM_ENABLE_PROJECTS="mlir;clang" \
    -DBUILD_SHARED_LIBS=ON \
    -DMLIR_ENABLE_BINDINGS_PYTHON=ON \
    -DPython3_EXECUTABLE="$(command -v python3)" \
    -DCMAKE_BUILD_TYPE=Release \
    -DLLVM_TARGETS_TO_BUILD="host"
}

build_llvm_min_required() {
  log "Building LLVM/MLIR targets required by PTOAS ..."
  ninja -C "$LLVM_BUILD_DIR" \
    llvm-tblgen \
    mlir-tblgen \
    MLIRPythonCAPI \
    MLIRMlirOptMain \
    MLIRPythonModules
}

configure_ptoas() {
  local pybind11_cmake_dir
  pybind11_cmake_dir="$(python3 -m pybind11 --cmakedir)"

  log "Configuring PTOAS at $PTO_SOURCE_DIR/build ..."
  cmake -G Ninja \
    -S "$PTO_SOURCE_DIR" \
    -B "$PTO_SOURCE_DIR/build" \
    -DLLVM_DIR="$LLVM_BUILD_DIR/lib/cmake/llvm" \
    -DMLIR_DIR="$LLVM_BUILD_DIR/lib/cmake/mlir" \
    -DPython3_EXECUTABLE="$(command -v python3)" \
    -DPython3_FIND_STRATEGY=LOCATION \
    -Dpybind11_DIR="$pybind11_cmake_dir" \
    -DMLIR_ENABLE_BINDINGS_PYTHON=ON \
    -DMLIR_PYTHON_PACKAGE_DIR="$LLVM_BUILD_DIR/tools/mlir/python_packages/mlir_core" \
    -DCMAKE_INSTALL_PREFIX="$PTO_INSTALL_DIR"
}

build_ptoas() {
  log "Building and installing PTOAS ..."
  ninja -C "$PTO_SOURCE_DIR/build"
  ninja -C "$PTO_SOURCE_DIR/build" install
}

write_env_script() {
  local env_file="$PTO_SOURCE_DIR/env.sh"
  log "Writing runtime env script: $env_file"
  cat >"$env_file" <<EOF
#!/usr/bin/env bash
# PTOAS runtime environment (generated by bootstrap.sh)
export WORKSPACE_DIR="$WORKSPACE_DIR"
export LLVM_SOURCE_DIR="$LLVM_SOURCE_DIR"
export LLVM_BUILD_DIR="$LLVM_BUILD_DIR"
export PTO_SOURCE_DIR="$PTO_SOURCE_DIR"
export PTO_INSTALL_DIR="$PTO_INSTALL_DIR"

# tools from pip --user
export PATH="\$HOME/.local/bin:\$PATH"

# Python path for MLIR core + PTO python package
export MLIR_PYTHON_ROOT="\$LLVM_BUILD_DIR/tools/mlir/python_packages/mlir_core"
export PTO_PYTHON_ROOT="\$PTO_INSTALL_DIR"
export PYTHONPATH="\$MLIR_PYTHON_ROOT:\$PTO_PYTHON_ROOT:\$PYTHONPATH"

# Shared libraries for LLVM/PTO runtime
export LD_LIBRARY_PATH="\$LLVM_BUILD_DIR/lib:\$PTO_INSTALL_DIR/lib:\$LD_LIBRARY_PATH"

# CLI tool
export PATH="\$PTO_SOURCE_DIR/build/tools/ptoas:\$PATH"
EOF
  chmod +x "$env_file"
}

update_bashrc() {
  local bashrc="$HOME/.bashrc"
  local start_marker="# >>> PTOAS environment >>>"
  local end_marker="# <<< PTOAS environment <<<"
  local source_line="source $PTO_SOURCE_DIR/env.sh"

  if [[ ! -f "$bashrc" ]]; then
    log "No ~/.bashrc found; skip auto-wiring."
    return
  fi

  if grep -Fq "$source_line" "$bashrc"; then
    log "~/.bashrc already contains PTOAS source line; skip."
    return
  fi

  log "Appending PTOAS env loading block into ~/.bashrc ..."
  {
    printf '\n%s\n' "$start_marker"
    printf '%s\n' "$source_line"
    printf '%s\n' "$end_marker"
  } >>"$bashrc"
}

print_summary() {
  cat <<EOF

[bootstrap] Done.

Key paths:
  WORKSPACE_DIR   = $WORKSPACE_DIR
  LLVM_SOURCE_DIR = $LLVM_SOURCE_DIR
  LLVM_BUILD_DIR  = $LLVM_BUILD_DIR
  PTO_SOURCE_DIR  = $PTO_SOURCE_DIR
  PTO_INSTALL_DIR = $PTO_INSTALL_DIR

Next:
  1) Run: source "$PTO_SOURCE_DIR/env.sh"
  2) Check CLI: ptoas --help
  3) Check Python:
     python3 - <<'PY'
from mlir.ir import Context, Module, Location
from mlir.dialects import pto
with Context() as ctx, Location.unknown():
    pto.register_dialect(ctx)
    Module.create()
print("PTO python binding OK")
PY
EOF
}

main() {
  require_cmd git
  require_cmd python3
  require_cmd gcc
  require_cmd g++

  # Ensure user-installed tools (cmake/ninja/pybind11-config) are visible.
  export PATH="$HOME/.local/bin:$PATH"

  install_python_deps

  require_cmd cmake
  require_cmd ninja

  clone_or_update_llvm
  configure_llvm
  build_llvm_min_required

  configure_ptoas
  build_ptoas

  write_env_script
  if [[ "$UPDATE_BASHRC" -eq 1 ]]; then
    update_bashrc
  else
    log "Skipping ~/.bashrc update (--no-bashrc)."
  fi

  print_summary
}

main "$@"
