#!/usr/bin/env bash
# Generated by ptoas-workspace-manager; source this file.
export PTO_SOURCE_DIR=/private/tmp/ptoas-workspaces/transforms-dir-consolidate
export PTO_BUILD_DIR=/private/tmp/ptoas-worktree-builds/transforms-dir-consolidate
export LLVM_BUILD_DIR=/Users/wanglan/Desktop/wanglanl/workspace/llvm-project-llvm19/build-shared-arm64
export PYTHON_BIN=/private/tmp/ptoas-workspaces/transforms-dir-consolidate/.venv/bin/python
source "$PTO_SOURCE_DIR/.venv/bin/activate"
export PTOAS_WORKSPACE_METADATA="$PTO_SOURCE_DIR/.ptoas-workspace.json"
