// Copyright (c) 2026 Huawei Technologies Co., Ltd.
// This program is free software, you can redistribute it and/or modify it under the terms and conditions of
// CANN Open Software License Agreement Version 2.0 (the "License").
// Please refer to the License for details. You may not use this file except in compliance with the License.
// THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
// INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
// See LICENSE in the root of the software repository for the full text of the License.

//===- VPTOBridgeWrapperGen.cpp - bridge wrapper source generation -------===//
//===----------------------------------------------------------------------===//
//
// Wrapper generation pass of the VPTO C++ interface bridge. The pipe family
// pass collects the wrapper specialization (TPipe/Tile/split C++ template
// tokens built from the op attributes plus the whitelist wrapper entry
// names) into the `pto.vpto.bridge.spec` module attribute; this pass renders
// that spec into the complete bridge wrapper C++ source and stores it in the
// `pto.vpto.bridge.wrapper_source` module attribute. Object emission then
// compiles the source with Bisheng (once per core kind, selected by the
// __DAV_CUBE__/__DAV_VEC__ guards) and links the bitcode into the device
// modules, replacing the former hand-written wrapper translation unit.
//
// The rendered structure follows the former hand-written wrapper: Pipe/Tile
// typedefs, a placement-new init entry, a sizeof size entry, the producer
// entry (TASSIGN + TPUSH) on the producing core, and the consumer entries
// (TPOP + barrier, TFREE) on the consuming core.
//
//===----------------------------------------------------------------------===//

#include "PTO/Transforms/VPTOBridgeTokens.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinAttributes.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/Pass/Pass.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/raw_ostream.h"

namespace mlir {
namespace pto {
namespace {

/// The pipe bridge specialization fields read from the spec DictionaryAttr.
struct BridgePipeSpec {
  StringRef pipe;
  StringRef producerTile;
  StringRef consumerTile;
  StringRef split;
  StringRef entryInit;
  StringRef entrySize;
  StringRef entryPush;
  StringRef entryPop;
  StringRef entryFree;
};

/// Renders the complete bridge wrapper source for the pipe specialization.
/// For a C2V pipe the cube core produces (push) and the vector core consumes
/// (pop/free); a V2C pipe swaps the roles. Each core section is guarded so
/// that compiling the same source per core kind yields exactly the entries
/// of that core.
FailureOr<std::string> renderPipeBridgeSource(const BridgePipeSpec &spec) {
  bool cubeProduces;
  if (spec.pipe.contains("pto::Direction::DIR_C2V")) {
    cubeProduces = true;
  } else if (spec.pipe.contains("pto::Direction::DIR_V2C")) {
    cubeProduces = false;
  } else {
    return failure();
  }

  std::string source;
  llvm::raw_string_ostream os(source);

  os << "// Generated by ptoas (pto-emit-vpto-bridge-wrapper). Do not edit.\n"
     << "// VPTO pipe bridge wrapper for " << spec.pipe << ".\n"
     << "#include <pto/pto-inst.hpp>\n"
     << "#include <pto/npu/a5/TFree.hpp>\n"
     << "#include <pto/npu/a5/TPop.hpp>\n"
     << "#include <pto/npu/a5/TPush.hpp>\n"
     << "#include <stddef.h>\n"
     << "#include <stdint.h>\n"
     << "\n"
     << "[aicore] inline void *operator new(size_t, void *ptr) noexcept { "
        "return ptr; }\n"
     << "\n"
     << "using Pipe = " << spec.pipe << ";\n"
     << "using ProducerTile = " << spec.producerTile << ";\n"
     << "using ConsumerTile = " << spec.consumerTile << ";\n"
     << "\n"
     << "extern \"C\" [aicore] void " << spec.entryInit
     << "(void *storage, uint32_t localBuffer) {\n"
     << "  new (storage) Pipe(nullptr, localBuffer, 0);\n"
     << "}\n"
     << "\n"
     << "extern \"C\" [aicore] size_t " << spec.entrySize
     << "() { return sizeof(Pipe); }\n"
     << "\n";

  auto renderPush = [&]() {
    os << "extern \"C\" [aicore] void " << spec.entryPush
       << "(void *storage, uint64_t producerAddress) {\n"
       << "  auto &pipe = *reinterpret_cast<Pipe *>(storage);\n"
       << "  ProducerTile tile;\n"
       << "  pto::TASSIGN_IMPL(tile, producerAddress);\n"
       << "  pto::TPUSH<Pipe, ProducerTile, " << spec.split
       << ">(pipe, tile);\n"
       << "}\n";
  };
  auto renderPop = [&]() {
    os << "extern \"C\" [aicore] uint64_t " << spec.entryPop
       << "(void *storage) {\n"
       << "  auto &pipe = *reinterpret_cast<Pipe *>(storage);\n"
       << "  ConsumerTile tile;\n"
       << "  pto::TPOP<Pipe, ConsumerTile, " << spec.split
       << ">(pipe, tile);\n"
       << "  pipe_barrier(PIPE_ALL);\n"
       << "  return reinterpret_cast<uint64_t>(tile.data());\n"
       << "}\n";
  };
  auto renderFree = [&]() {
    os << "extern \"C\" [aicore] void " << spec.entryFree
       << "(void *storage) {\n"
       << "  auto &pipe = *reinterpret_cast<Pipe *>(storage);\n"
       << "  pto::TFREE<Pipe, " << spec.split << ">(pipe);\n"
       << "}\n";
  };

  os << "#ifdef __DAV_CUBE__\n";
  if (cubeProduces) {
    renderPush();
  } else {
    renderPop();
    os << "\n";
    renderFree();
  }
  os << "#endif\n"
     << "\n"
     << "#ifdef __DAV_VEC__\n";
  if (cubeProduces) {
    renderPop();
    os << "\n";
    renderFree();
  } else {
    renderPush();
  }
  os << "#endif\n";

  os.flush();
  return source;
}

/// Merges the per-function bridge specs collected by the family pass into the
/// module-level spec attribute. Identical fields deduplicate; a field with
/// two different values (e.g. two pipe configurations) is a conflict. The
/// functions are visited in module order, so the merge is deterministic.
static LogicalResult mergeFuncSpecsIntoModule(ModuleOp module) {
  SmallVector<func::FuncOp> specFuncs;
  for (auto func : module.getOps<func::FuncOp>()) {
    if (func->getAttrOfType<DictionaryAttr>(kBridgeFuncSpecAttrName))
      specFuncs.push_back(func);
  }
  if (specFuncs.empty())
    return success();

  SmallVector<NamedAttribute> merged;
  for (func::FuncOp func : specFuncs) {
    auto funcSpec = func->getAttrOfType<DictionaryAttr>(kBridgeFuncSpecAttrName);
    for (NamedAttribute field : funcSpec) {
      bool found = false;
      for (NamedAttribute existing : merged) {
        if (existing.getName() != field.getName())
          continue;
        if (existing.getValue() != field.getValue()) {
          func.emitError()
              << "VPTO pipe bridge: conflicting pipe bridge specialization "
                 "across functions; the pipe configuration must be identical";
          return failure();
        }
        found = true;
        break;
      }
      if (!found)
        merged.push_back(field);
    }
    func->removeAttr(kBridgeFuncSpecAttrName);
  }

  module->setAttr(kBridgeSpecAttrName,
                  DictionaryAttr::get(module.getContext(), merged));
  return success();
}

struct VPTOBridgeWrapperGenPass final
    : public PassWrapper<VPTOBridgeWrapperGenPass, OperationPass<ModuleOp>> {
  MLIR_DEFINE_EXPLICIT_INTERNAL_INLINE_TYPE_ID(VPTOBridgeWrapperGenPass)

  VPTOBridgeWrapperGenPass() = default;
  VPTOBridgeWrapperGenPass(const VPTOBridgeWrapperGenPass &other)
      : PassWrapper(other) {
    copyOptionValuesFrom(&other);
  }

  llvm::StringRef getArgument() const final {
    return "pto-emit-vpto-bridge-wrapper";
  }

  llvm::StringRef getDescription() const final {
    return "Render the VPTO bridge wrapper source from the collected spec";
  }

  void runOnOperation() override {
    ModuleOp module = getOperation();

    // Merge the per-function specs into the module spec first: the family
    // pass instances may have run concurrently and only write their own
    // function attribute, so this single-threaded pass owns the module
    // attribute.
    if (failed(mergeFuncSpecsIntoModule(module))) {
      signalPassFailure();
      return;
    }

    auto specAttr =
        module->getAttrOfType<DictionaryAttr>(kBridgeSpecAttrName);
    if (!specAttr) {
      // No pipe bridge specialization was collected; nothing to generate.
      return;
    }

    // All spec fields are mandatory: a pipe bridge kernel always carries the
    // full init/size/push/pop/free entry set with a single pipe and tile
    // pair configuration.
    BridgePipeSpec spec;
    struct {
      llvm::StringLiteral key;
      StringRef *field;
    } fields[] = {
        {kBridgeSpecPipeKey, &spec.pipe},
        {kBridgeSpecProducerTileKey, &spec.producerTile},
        {kBridgeSpecConsumerTileKey, &spec.consumerTile},
        {kBridgeSpecSplitKey, &spec.split},
        {kBridgeSpecEntryInitKey, &spec.entryInit},
        {kBridgeSpecEntrySizeKey, &spec.entrySize},
        {kBridgeSpecEntryPushKey, &spec.entryPush},
        {kBridgeSpecEntryPopKey, &spec.entryPop},
        {kBridgeSpecEntryFreeKey, &spec.entryFree},
    };
    for (const auto &field : fields) {
      auto value = specAttr.getAs<StringAttr>(field.key);
      if (!value || value.getValue().empty()) {
        module.emitError()
            << "VPTO pipe bridge spec is missing the '" << field.key
            << "' field; the pipe family pass must collect it before "
               "wrapper generation";
        signalPassFailure();
        return;
      }
      *field.field = value.getValue();
    }

    FailureOr<std::string> source = renderPipeBridgeSource(spec);
    if (failed(source)) {
      module.emitError()
          << "VPTO pipe bridge: cannot render the wrapper source; the pipe "
             "token must carry a C2V or V2C direction";
      signalPassFailure();
      return;
    }

    OpBuilder builder(module);
    module->setAttr(kBridgeWrapperSourceAttrName,
                    builder.getStringAttr(*source));
    module->removeAttr(kBridgeSpecAttrName);
  }
};

} // namespace

std::unique_ptr<Pass> createVPTOBridgeWrapperGenPass() {
  return std::make_unique<VPTOBridgeWrapperGenPass>();
}

} // namespace pto
} // namespace mlir
