// Copyright (c) 2026 Huawei Technologies Co., Ltd.
// This program is free software, you can redistribute it and/or modify it under the terms and conditions of
// CANN Open Software License Agreement Version 2.0 (the "License").
// Please refer to the License for details. You may not use this file except in compliance with the License.
// THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
// INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
// See LICENSE in the root of the software repository for the full text of the License.

//===- VPTOBridgeWrapperGen.cpp - bridge wrapper source generation -------===//
//===----------------------------------------------------------------------===//
//
// Wrapper generation pass of the VPTO C++ interface bridge. The family
// passes collect the wrapper specialization (C++ template tokens built from
// the op attributes/operand types plus the whitelist wrapper entry names)
// into per-function attributes; this pass merges them into the module spec
// and renders it into the complete bridge wrapper C++ source, stored in the
// `pto.vpto.bridge.wrapper_source` module attribute. Object emission then
// compiles the source with Bisheng (once per core kind, selected by the
// __DAV_CUBE__/__DAV_VEC__ guards) and links the bitcode into the device
// modules, replacing the former hand-written wrapper translation unit.
//
// Two families render today: the pipe family (Pipe/Tile typedefs, a
// placement-new init entry, a sizeof size entry, and the producer/consumer
// entries placed on the cores implied by the pipe direction) and the matmul
// family (three/four tile typedefs plus TMATMUL/TMATMUL_ACC entries, all
// cube-side).
//
//===----------------------------------------------------------------------===//

#include "PTO/Transforms/VPTOBridgeTokens.h"
#include "PTO/Transforms/VPTOBridgeWhitelist.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinAttributes.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/Pass/Pass.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/StringSet.h"
#include "llvm/Support/raw_ostream.h"

namespace mlir {
namespace pto {
namespace {

/// The pipe bridge specialization fields read from the spec DictionaryAttr.
struct BridgePipeSpec {
  StringRef pipe;
  StringRef producerTile;
  StringRef consumerTile;
  StringRef split;
  StringRef entryInit;
  StringRef entrySize;
  StringRef entryPush;
  StringRef entryPop;
  StringRef entryFree;
};

/// The matmul bridge specialization fields read from the spec
/// DictionaryAttr. The acc phase is empty when the calls render without a
/// template argument; the accumulate fields are only present when the
/// module carries a tmatmul.acc.
struct BridgeMatmulSpec {
  StringRef leftTile;
  StringRef rightTile;
  StringRef resultTile;
  StringRef accInTile;
  StringRef accPhase;
  StringRef entryMatmul;
  StringRef entryMatmulAcc;
};

/// Renders the complete bridge wrapper source for the pipe specialization.
/// For a C2V pipe the cube core produces (push) and the vector core consumes
/// (pop/free); a V2C pipe swaps the roles. Each core section is guarded so
/// that compiling the same source per core kind yields exactly the entries
/// of that core.
FailureOr<std::string> renderPipeBridgeSource(const BridgePipeSpec &spec) {
  bool cubeProduces;
  if (spec.pipe.contains("pto::Direction::DIR_C2V")) {
    cubeProduces = true;
  } else if (spec.pipe.contains("pto::Direction::DIR_V2C")) {
    cubeProduces = false;
  } else {
    return failure();
  }

  std::string source;
  llvm::raw_string_ostream os(source);

  os << "// Generated by ptoas (pto-emit-vpto-bridge-wrapper). Do not edit.\n"
     << "// VPTO pipe bridge wrapper for " << spec.pipe << ".\n"
     << "#include <pto/pto-inst.hpp>\n"
     << "#include <pto/npu/a5/TFree.hpp>\n"
     << "#include <pto/npu/a5/TPop.hpp>\n"
     << "#include <pto/npu/a5/TPush.hpp>\n"
     << "#include <stddef.h>\n"
     << "#include <stdint.h>\n"
     << "\n"
     << "[aicore] inline void *operator new(size_t, void *ptr) noexcept { "
        "return ptr; }\n"
     << "\n"
     << "using Pipe = " << spec.pipe << ";\n"
     << "using ProducerTile = " << spec.producerTile << ";\n"
     << "using ConsumerTile = " << spec.consumerTile << ";\n"
     << "\n"
     << "extern \"C\" [aicore] void " << spec.entryInit
     << "(void *storage, uint32_t localBuffer) {\n"
     << "  new (storage) Pipe(nullptr, localBuffer, 0);\n"
     << "}\n"
     << "\n"
     << "extern \"C\" [aicore] size_t " << spec.entrySize
     << "() { return sizeof(Pipe); }\n"
     << "\n";

  auto renderPush = [&]() {
    os << "extern \"C\" [aicore] void " << spec.entryPush
       << "(void *storage, uint64_t producerAddress) {\n"
       << "  auto &pipe = *reinterpret_cast<Pipe *>(storage);\n"
       << "  ProducerTile tile;\n"
       << "  pto::TASSIGN_IMPL(tile, producerAddress);\n"
       << "  pto::TPUSH<Pipe, ProducerTile, " << spec.split
       << ">(pipe, tile);\n"
       << "}\n";
  };
  auto renderPop = [&]() {
    os << "extern \"C\" [aicore] uint64_t " << spec.entryPop
       << "(void *storage) {\n"
       << "  auto &pipe = *reinterpret_cast<Pipe *>(storage);\n"
       << "  ConsumerTile tile;\n"
       << "  pto::TPOP<Pipe, ConsumerTile, " << spec.split
       << ">(pipe, tile);\n"
       << "  pipe_barrier(PIPE_ALL);\n"
       << "  return reinterpret_cast<uint64_t>(tile.data());\n"
       << "}\n";
  };
  auto renderFree = [&]() {
    os << "extern \"C\" [aicore] void " << spec.entryFree
       << "(void *storage) {\n"
       << "  auto &pipe = *reinterpret_cast<Pipe *>(storage);\n"
       << "  pto::TFREE<Pipe, " << spec.split << ">(pipe);\n"
       << "}\n";
  };

  os << "#ifdef __DAV_CUBE__\n";
  if (cubeProduces) {
    renderPush();
  } else {
    renderPop();
    os << "\n";
    renderFree();
  }
  os << "#endif\n"
     << "\n"
     << "#ifdef __DAV_VEC__\n";
  if (cubeProduces) {
    renderPop();
    os << "\n";
    renderFree();
  } else {
    renderPush();
  }
  os << "#endif\n";

  os.flush();
  return source;
}

/// Renders the complete bridge wrapper source for the matmul specialization.
/// Matmul is cube-only, so every entry lives under the __DAV_CUBE__ guard;
/// the vec half of the wrapper compiles empty. Each tile is bound to its
/// planned address with TASSIGN before the TMATMUL/TMATMUL_ACC call.
FailureOr<std::string>
renderMatmulBridgeSource(const BridgeMatmulSpec &spec) {
  std::string source;
  llvm::raw_string_ostream os(source);

  std::string phaseTmpl;
  if (!spec.accPhase.empty()) {
    phaseTmpl = ("<" + spec.accPhase + ">").str();
  }

  os << "// Generated by ptoas (pto-emit-vpto-bridge-wrapper). Do not edit.\n"
     << "// VPTO matmul bridge wrapper.\n"
     << "#include <pto/pto-inst.hpp>\n"
     << "#include <pto/npu/a5/TMatmul.hpp>\n"
     << "#include <stdint.h>\n"
     << "\n"
     << "using LeftTile = " << spec.leftTile << ";\n"
     << "using RightTile = " << spec.rightTile << ";\n"
     << "using ResultTile = " << spec.resultTile << ";\n";
  if (!spec.accInTile.empty()) {
    os << "using AccInTile = " << spec.accInTile << ";\n";
  }
  os << "\n"
     << "#ifdef __DAV_CUBE__\n";
  if (!spec.entryMatmul.empty()) {
    os << "extern \"C\" [aicore] void " << spec.entryMatmul
       << "(uint64_t dstAddress, uint64_t lhsAddress, uint64_t rhsAddress) "
          "{\n"
       << "  ResultTile dst;\n"
       << "  LeftTile lhs;\n"
       << "  RightTile rhs;\n"
       << "  pto::TASSIGN_IMPL(dst, dstAddress);\n"
       << "  pto::TASSIGN_IMPL(lhs, lhsAddress);\n"
       << "  pto::TASSIGN_IMPL(rhs, rhsAddress);\n"
       << "  pto::TMATMUL" << phaseTmpl << "(dst, lhs, rhs);\n"
       << "}\n";
  }
  if (!spec.entryMatmul.empty() && !spec.entryMatmulAcc.empty()) {
    os << "\n";
  }
  if (!spec.entryMatmulAcc.empty()) {
    os << "extern \"C\" [aicore] void " << spec.entryMatmulAcc
       << "(uint64_t dstAddress, uint64_t accInAddress, uint64_t lhsAddress, "
          "uint64_t rhsAddress) {\n"
       << "  ResultTile dst;\n"
       << "  AccInTile accIn;\n"
       << "  LeftTile lhs;\n"
       << "  RightTile rhs;\n"
       << "  pto::TASSIGN_IMPL(dst, dstAddress);\n"
       << "  pto::TASSIGN_IMPL(accIn, accInAddress);\n"
       << "  pto::TASSIGN_IMPL(lhs, lhsAddress);\n"
       << "  pto::TASSIGN_IMPL(rhs, rhsAddress);\n"
       << "  pto::TMATMUL_ACC" << phaseTmpl << "(dst, accIn, lhs, rhs);\n"
       << "}\n";
  }
  os << "#endif\n";

  os.flush();
  return source;
}

/// Merges the per-function bridge specs collected by the family pass into the
/// module-level spec attribute. Identical fields deduplicate; a field with
/// two different values (e.g. two pipe configurations) is a conflict. The
/// functions are visited in module order, so the merge is deterministic.
static LogicalResult mergeFuncSpecsIntoModule(ModuleOp module) {
  SmallVector<func::FuncOp> specFuncs;
  for (auto func : module.getOps<func::FuncOp>()) {
    if (func->getAttrOfType<DictionaryAttr>(kBridgeFuncSpecAttrName))
      specFuncs.push_back(func);
  }
  if (specFuncs.empty())
    return success();

  SmallVector<NamedAttribute> merged;
  for (func::FuncOp func : specFuncs) {
    auto funcSpec = func->getAttrOfType<DictionaryAttr>(kBridgeFuncSpecAttrName);
    for (NamedAttribute field : funcSpec) {
      bool found = false;
      for (NamedAttribute existing : merged) {
        if (existing.getName() != field.getName())
          continue;
        if (existing.getValue() != field.getValue()) {
          func.emitError()
              << "VPTO bridge: conflicting bridge specialization across "
                 "functions; the family configurations must be identical";
          return failure();
        }
        found = true;
        break;
      }
      if (!found)
        merged.push_back(field);
    }
    func->removeAttr(kBridgeFuncSpecAttrName);
  }

  module->setAttr(kBridgeSpecAttrName,
                  DictionaryAttr::get(module.getContext(), merged));
  return success();
}

/// Maps a tmpl_map `source` to the spec keys that must carry a collected
/// token for the declaration to be covered. The pipe `tile` source feeds
/// both role tiles; unknown sources are rejected at whitelist parse time.
static llvm::SmallVector<llvm::StringLiteral, 2>
tmplMapSourceSpecKeys(llvm::StringRef source) {
  if (source == "pipe.init")
    return {kBridgeSpecPipeKey};
  if (source == "tile")
    return {kBridgeSpecProducerTileKey, kBridgeSpecConsumerTileKey};
  if (source == "left_tile")
    return {kBridgeSpecLeftTileKey};
  if (source == "right_tile")
    return {kBridgeSpecRightTileKey};
  if (source == "result_tile")
    return {kBridgeSpecResultTileKey};
  if (source == "acc_in_tile")
    return {kBridgeSpecAccInTileKey};
  return {};
}

/// Validates the tmpl_map declarations of the whitelist entries used by the
/// module: every declared template slot must be covered by a token the
/// family pass collected into the spec. Field-level template argument
/// construction stays authoritative in VPTOBridgeTokens (design decision 4);
/// this check only guarantees the declarations are not silently dropped.
static LogicalResult
validateTmplMapCoverage(ModuleOp module, const BridgeWhitelist &whitelist,
                        DictionaryAttr specAttr) {
  llvm::StringSet<> usedEntries;
  constexpr llvm::StringLiteral entryKeys[] = {
      kBridgeSpecEntryInitKey,     kBridgeSpecEntrySizeKey,
      kBridgeSpecEntryPushKey,     kBridgeSpecEntryPopKey,
      kBridgeSpecEntryFreeKey,     kBridgeSpecEntryMatmulKey,
      kBridgeSpecEntryMatmulAccKey,
  };
  for (llvm::StringLiteral key : entryKeys) {
    if (auto value = specAttr.getAs<StringAttr>(key))
      usedEntries.insert(value.getValue());
  }

  for (const BridgeWhitelistEntry &entry : whitelist.bridgeOps) {
    if (!usedEntries.count(entry.entry))
      continue;
    for (const BridgeTmplMapField &row : entry.tmplMap) {
      for (llvm::StringLiteral key : tmplMapSourceSpecKeys(row.source)) {
        auto value = specAttr.getAs<StringAttr>(key);
        if (value && !value.getValue().empty())
          continue;
        module.emitError()
            << "VPTO bridge: whitelist entry '" << entry.entry
            << "' declares tmpl_map target '" << row.target
            << "' from source '" << row.source
            << "', but no token was collected for it";
        return failure();
      }
    }
  }
  return success();
}

struct VPTOBridgeWrapperGenPass final
    : public PassWrapper<VPTOBridgeWrapperGenPass, OperationPass<ModuleOp>> {
  MLIR_DEFINE_EXPLICIT_INTERNAL_INLINE_TYPE_ID(VPTOBridgeWrapperGenPass)

  VPTOBridgeWrapperGenPass() = default;
  VPTOBridgeWrapperGenPass(const VPTOBridgeWrapperGenPass &other)
      : PassWrapper(other) {
    copyOptionValuesFrom(&other);
  }

  Option<std::string> whitelistPath{
      *this, "whitelist-path", llvm::cl::init(""),
      llvm::cl::desc("Path to the VPTO bridge whitelist YAML; falls back to "
                     "the PTOAS_VPTO_BRIDGE_WHITELIST environment variable, "
                     "then to the built-in default whitelist")};

  llvm::StringRef getArgument() const final {
    return "pto-emit-vpto-bridge-wrapper";
  }

  llvm::StringRef getDescription() const final {
    return "Render the VPTO bridge wrapper source from the collected spec";
  }

  void runOnOperation() override {
    ModuleOp module = getOperation();

    // Merge the per-function specs into the module spec first: the family
    // pass instances may have run concurrently and only write their own
    // function attribute, so this single-threaded pass owns the module
    // attribute.
    if (failed(mergeFuncSpecsIntoModule(module))) {
      signalPassFailure();
      return;
    }

    auto specAttr =
        module->getAttrOfType<DictionaryAttr>(kBridgeSpecAttrName);
    if (!specAttr) {
      // No bridge specialization was collected; nothing to generate.
      return;
    }

    // Consume the whitelist: the tmpl_map declarations of the entries this
    // module uses must be covered by the collected specialization.
    FailureOr<BridgeWhitelist> whitelistOr =
        loadBridgeWhitelist(whitelistPath, llvm::errs());
    if (failed(whitelistOr)) {
      signalPassFailure();
      return;
    }
    if (failed(validateTmplMapCoverage(module, *whitelistOr, specAttr))) {
      signalPassFailure();
      return;
    }

    bool hasPipeFields = specAttr.getAs<StringAttr>(kBridgeSpecPipeKey) != nullptr;
    bool hasMatmulFields =
        specAttr.getAs<StringAttr>(kBridgeSpecLeftTileKey) != nullptr;
    if (hasPipeFields && hasMatmulFields) {
      module.emitError()
          << "VPTO bridge: mixing the pipe and matmul bridge families in "
             "one module is not supported yet";
      signalPassFailure();
      return;
    }

    FailureOr<std::string> source = failure();
    if (hasMatmulFields) {
      BridgeMatmulSpec spec;
      struct {
        llvm::StringLiteral key;
        StringRef *field;
        bool mandatory;
      } fields[] = {
          {kBridgeSpecLeftTileKey, &spec.leftTile, /*mandatory=*/true},
          {kBridgeSpecRightTileKey, &spec.rightTile, /*mandatory=*/true},
          {kBridgeSpecResultTileKey, &spec.resultTile, /*mandatory=*/true},
          {kBridgeSpecAccInTileKey, &spec.accInTile, /*mandatory=*/false},
          {kBridgeSpecAccPhaseKey, &spec.accPhase, /*mandatory=*/false},
          {kBridgeSpecEntryMatmulKey, &spec.entryMatmul,
           /*mandatory=*/false},
          {kBridgeSpecEntryMatmulAccKey, &spec.entryMatmulAcc,
           /*mandatory=*/false},
      };
      bool ok = true;
      for (const auto &field : fields) {
        auto value = specAttr.getAs<StringAttr>(field.key);
        if (value)
          *field.field = value.getValue();
        if (field.mandatory && field.field->empty()) {
          module.emitError()
              << "VPTO matmul bridge spec is missing the '" << field.key
              << "' field; the matmul family pass must collect it before "
                 "wrapper generation";
          ok = false;
        }
      }
      if (ok && spec.entryMatmul.empty() && spec.entryMatmulAcc.empty()) {
        module.emitError()
            << "VPTO matmul bridge spec carries no wrapper entry; the "
               "matmul family pass must collect entry.matmul or "
               "entry.matmul_acc before wrapper generation";
        ok = false;
      }
      if (ok)
        source = renderMatmulBridgeSource(spec);
    } else {
      // All pipe spec fields are mandatory: a pipe bridge kernel always
      // carries the full init/size/push/pop/free entry set with a single
      // pipe and tile pair configuration.
      BridgePipeSpec spec;
      struct {
        llvm::StringLiteral key;
        StringRef *field;
      } fields[] = {
          {kBridgeSpecPipeKey, &spec.pipe},
          {kBridgeSpecProducerTileKey, &spec.producerTile},
          {kBridgeSpecConsumerTileKey, &spec.consumerTile},
          {kBridgeSpecSplitKey, &spec.split},
          {kBridgeSpecEntryInitKey, &spec.entryInit},
          {kBridgeSpecEntrySizeKey, &spec.entrySize},
          {kBridgeSpecEntryPushKey, &spec.entryPush},
          {kBridgeSpecEntryPopKey, &spec.entryPop},
          {kBridgeSpecEntryFreeKey, &spec.entryFree},
      };
      bool ok = true;
      for (const auto &field : fields) {
        auto value = specAttr.getAs<StringAttr>(field.key);
        if (!value || value.getValue().empty()) {
          module.emitError()
              << "VPTO pipe bridge spec is missing the '" << field.key
              << "' field; the pipe family pass must collect it before "
                 "wrapper generation";
          ok = false;
          break;
        }
        *field.field = value.getValue();
      }
      if (ok) {
        source = renderPipeBridgeSource(spec);
        if (failed(source)) {
          module.emitError()
              << "VPTO pipe bridge: cannot render the wrapper source; the "
                 "pipe token must carry a C2V or V2C direction";
        }
      }
    }
    if (failed(source)) {
      signalPassFailure();
      return;
    }

    OpBuilder builder(module);
    module->setAttr(kBridgeWrapperSourceAttrName,
                    builder.getStringAttr(*source));
    module->removeAttr(kBridgeSpecAttrName);
  }
};

} // namespace

std::unique_ptr<Pass> createVPTOBridgeWrapperGenPass() {
  return std::make_unique<VPTOBridgeWrapperGenPass>();
}

} // namespace pto
} // namespace mlir
