// Copyright (c) 2026 Huawei Technologies Co., Ltd.
// Compatibility aggregate for PTO Tile operation families.
#ifndef MLIR_DIALECT_PTO_IR_PTOTILEOPS
#define MLIR_DIALECT_PTO_IR_PTOTILEOPS
include "PTO/IR/PTOTileMemoryOps.td"
include "PTO/IR/PTOTileCubeOps.td"
include "PTO/IR/PTOTilePipelineOps.td"
include "PTO/IR/PTOTileVectorDataOps.td"
include "PTO/IR/PTOTileVectorElementwiseOps.td"
include "PTO/IR/PTOTileVectorReductionOps.td"
#endif
