#ifndef MLIR_DIALECT_PTO_IR_PTOTILEVECTORELEMENTWISE_H_
#define MLIR_DIALECT_PTO_IR_PTOTILEVECTORELEMENTWISE_H_
#include "PTO/IR/PTOCommon.h"
#define GET_OP_CLASSES
#include "PTO/IR/PTOTileVectorElementwiseOps.h.inc"
#endif
