#ifndef MLIR_DIALECT_PTO_IR_PTOTILEVECTORREDUCTION_H_
#define MLIR_DIALECT_PTO_IR_PTOTILEVECTORREDUCTION_H_
#include "PTO/IR/PTOCommon.h"
#define GET_OP_CLASSES
#include "PTO/IR/PTOTileVectorReductionOps.h.inc"
#endif
