#!/usr/bin/env python3
# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.

"""A5 SIMT ST: per-element ``pto.Vec(..., init=sequence)`` pack cases (issue #1242 requirement 1).

Each lane reads *size* distinct runtime scalars and writes them back as one packed
vector (a single aligned store). All cases are generated by the shared factory
``_make_pack_case`` from the ``_CASE_SPECS`` table below; dtype/size combos: f32x2,
f16x2/x4, i16x2/x4, i8x2/x4, i32/ui32/si32 x2, i64x2. Instruction-layer evidence
(single 64-bit STS for 32-bit-element pairs, per-element stores for 8/16-bit integer
packs, etc.) is recorded in the PR description.
"""

import numpy as np

from common import auto_main, golden_output_case
from ptodsl import pto
from ptodsl import scalar


LANES = 32


def _float_recipe(count):
    return (np.arange(count, dtype=np.float64) * 0.25) - 5.0


def _int_recipe(modulus, offset):
    def recipe(count):
        return (np.arange(count, dtype=np.int64) * 7) % modulus - offset

    return recipe


# name, PTO dtype, NumPy dtype, vector size, host input recipe
_CASE_SPECS = [
    ("vec_f32x2", pto.f32, np.float32, 2, _float_recipe),
    ("vec_f16x2", pto.f16, np.float16, 2, _float_recipe),
    ("vec_f16x4", pto.f16, np.float16, 4, _float_recipe),
    ("vec_i16x2", pto.i16, np.int16, 2, _int_recipe(1 << 16, 1 << 15)),
    ("vec_i16x4", pto.i16, np.int16, 4, _int_recipe(1 << 16, 1 << 15)),
    ("vec_i8x2", pto.i8, np.int8, 2, _int_recipe(1 << 8, 1 << 7)),
    ("vec_i8x4", pto.i8, np.int8, 4, _int_recipe(1 << 8, 1 << 7)),
    ("vec_i32x2", pto.i32, np.int32, 2, _int_recipe(1 << 32, 1 << 31)),
    ("vec_ui32x2", pto.ui32, np.uint32, 2, _float_recipe),
    ("vec_si32x2", pto.si32, np.int32, 2, _int_recipe(1 << 32, 1 << 31)),
    ("vec_i64x2", pto.i64, np.int64, 2, _int_recipe(1 << 62, 1 << 61)),
]


def _make_pack_case(name, dtype, np_dtype, size, recipe):
    """Build one pack-and-store ST case: lane ``tid`` packs ``inp[tid*size .. +size)``
    into one ``pto.Vec(dtype, size, init=...)`` and writes it to ``out[tid*size .. +size)``."""

    @pto.simt(name=f"{name}_body")
    def pack_body(inp: pto.ptr(dtype, "gm"), out: pto.ptr(dtype, "gm")):
        tid = pto.get_tid_x()
        pack = pto.Vec(dtype, size, init=tuple(
            scalar.load(inp, scalar.index_cast(tid * size + index))
            for index in pto.static_range(size)
        ))
        scalar.store(pack, out, scalar.index_cast(tid * size))

    @pto.jit(
        name=f"{name}_kernel",
        kernel_kind="vector",
        target="a5",
        mode="explicit",
        insert_sync=False,
    )
    def pack_kernel(inp_ptr: pto.ptr(dtype, "gm"), out_ptr: pto.ptr(dtype, "gm")):
        pack_body[LANES, 1, 1](inp_ptr, out_ptr)
        pto.pipe_barrier(pto.Pipe.ALL)

    def make_inputs():
        return [recipe(LANES * size).astype(np_dtype)]

    def make_expected(inp):
        # The golden is the input itself; every element is distinct, so a broadcast
        # or reordered implementation cannot pass.
        return inp

    return golden_output_case(
        name,
        pack_kernel,
        inputs=make_inputs,
        expected=make_expected,
        rtol=0.0,
        atol=0.0,
    )


CASES = [_make_pack_case(*spec) for spec in _CASE_SPECS]


auto_main(globals())
