# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.

"""Check emitted event-lane balance for the three-slot transitive-sync fixture.

This checks compiler output, without executing a kernel: enumerate each lane's
set/wait order and compare the necessary boundary flags with the final SyncIR.
Unlike the compiler's residue formula, the oracle uses first-use enumeration.
"""

import argparse
from collections import Counter
from pathlib import Path
import re


def read_events(path):
    """Extract the one steady-state loop and its allocated event operations."""
    text = path.read_text(encoding="utf-8").split("After EventId Allocation", 1)[1]
    nodes = list(re.finditer(r"^\s*\[\s*(\d+)\]\s+(COMPOUND|LOOP) (.*)$", text, re.MULTILINE))
    begin = next(int(node[1]) for node in nodes if "LOOP_BEGIN" in node[3])
    end = next(int(node[1]) for node in nodes if "LOOP_END" in node[3])
    events = []
    pattern = re.compile(
        r"(set_flag|wait_flag) <(PIPE_\w+) -> (PIPE_\w+)> idx=(\d+)"
        r".*eventIdNum=3 eventIds=\[([\d,]+)\]"
    )
    for index, node in enumerate(nodes):
        stop = nodes[index + 1].start() if index + 1 < len(nodes) else len(text)
        offset = 2 if "pto.tload " in node[3] else 0
        for event in pattern.finditer(text[node.end():stop]):
            events.append((int(node[1]), event[1], (event[2], event[3]), int(event[4]),
                           tuple(map(int, event[5].split(","))), offset))
    return begin, end, events


def expected_boundary(actions, lower, upper):
    """Enumerate first visits and token consumption for one event family."""
    count = 3
    first = {}
    for iv in range(lower, lower + count):
        for _, kind, offset in actions:
            first.setdefault((iv + offset) % count, kind)
    initial = {lane for lane, kind in first.items() if kind == "wait_flag"}
    pending = set(initial)
    for iv in range(lower, upper):
        for _, kind, offset in actions:
            lane = (iv + offset) % count
            if kind == "wait_flag":
                if lane not in pending:
                    raise ValueError(f"missing token at iteration {iv}, lane {lane}")
                pending.remove(lane)
            else:
                if lane in pending:
                    raise ValueError(f"unconsumed token overwritten at iteration {iv}, lane {lane}")
                pending.add(lane)
    return initial, pending


def check_boundaries(path, lower, upper):
    """Match the final SyncIR primes/drains to the independently enumerated lanes."""
    begin, end, events = read_events(path)
    groups = {}
    actual = Counter()
    for node, kind, pipes, group, ids, offset in events:
        if begin < node < end and len(ids) == 3:
            groups.setdefault(group, []).append((node, kind, pipes, ids, offset))
        elif node == begin and kind == "set_flag" and len(ids) == 1:
            actual[("prime", pipes, ids[0])] += 1
        elif node == end and kind == "wait_flag" and len(ids) == 1:
            actual[("drain", pipes, ids[0])] += 1
    if len(groups) != 4:
        raise ValueError(f"expected four necessary rotating event families, found {len(groups)}")
    expected = Counter()
    for pair in groups.values():
        if len(pair) != 2 or {event[1] for event in pair} != {"set_flag", "wait_flag"}:
            raise ValueError(f"unpaired rotating event: {pair}")
        pipes, ids = pair[0][2:4]
        if pair[1][2:4] != (pipes, ids):
            raise ValueError("set and wait use different event arrays")
        actions = sorted(
            ((node, kind, offset) for node, kind, _, _, offset in pair),
            key=lambda action: (action[0], action[1] == "set_flag"),
        )
        prime, drain = expected_boundary(actions, lower, upper)
        for label, lanes in (("prime", prime), ("drain", drain)):
            expected.update((label, pipes, ids[lane]) for lane in lanes)
    if actual != expected:
        raise ValueError(f"boundary mismatch: missing={expected - actual}, extra={actual - expected}")
    print(f"slot event boundaries verified for [{lower}, {upper})")


def main():
    """Validate one compiler dump generated by the neighboring lit fixture."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("log", type=Path)
    parser.add_argument("--lower", type=int, default=0)
    parser.add_argument("--upper", type=int, default=62)
    args = parser.parse_args()
    if not 0 <= args.lower < args.upper <= 4096:
        parser.error("expected 0 <= lower < upper <= 4096")
    check_boundaries(args.log, args.lower, args.upper)


if __name__ == "__main__":
    main()
